### ISSUE TITLE
Not working anymore on 4.7.3

### ISSUE THREAD

**Issue by mxmkmarquette** [pablo-pacheco/file-renaming-on-upload#1]
Fatal error: Uncaught Error: Class ‘FROU\Plugin_Core’ not found in /home/madmax/public_html/neufsvies/wp-content/plugins/file-renaming-on-upload/file-renaming-on-upload.php:29 Stack trace: #0 /home/madmax/public_html/wp-admin/includes/plugin.php(1882): include() #1 /home/madmax/public_html/wp-admin/plugins.php(164): plugin_sandbox_scrape(‘file-renaming-o…’) #2 {main} thrown in /home/madmax/public_html/neufsvies/wp-content/plugins/file-renaming-on-upload/file-renaming-on-upload.php on line 29

php 7.0.16
wordpress 4.7.3

**Comment by pablo-pacheco** [comment]
Thanks for pointing that out.
What OS are you using?

I think it maybe a problem on autoloader. I'm going to check it

**Comment by pablo-pacheco** [comment]
Any chance you give me access to your site?

**Comment by mxmkmarquette** [comment]
yes i can what's you email

**Comment by pablo-pacheco** [comment]
Thanks.
pablo.sg.pacheco@gmail.com
Em 09/04/2017 02:18, "mxmkmarquette" <notifications@github.com> escreveu:

**Comment by pablo-pacheco** [comment]
I believe i could fix the error. I really want to thank you!
I've updated the plugin to version 2.0.1.

Take care :)
